source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'omniauth'
gem 'devise_token_auth'

gem 'rails', '~> 5.0.2'

gem 'pg', '~> 0.18'

gem 'puma', '~> 3.0'

gem 'rack-cors'

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'active_model_serializers', '~> 0.10.0'

group :development do
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'letter_opener'
  gem 'spring-commands-rspec'
  gem 'spring-watcher-listen'
  gem 'web-console'
  gem 'rubocop'
  gem 'terminal-notifier-guard'
end

group :development, :test do
  gem 'awesome_print'
  gem 'bullet'
  gem 'factory_girl_rails'
  gem 'pry-rails'
  gem 'rspec-rails', '~> 3.5.2'
  gem 'faker'
  gem 'dotenv'
end

group :test do
  gem 'capybara'
  gem 'codeclimate-test-reporter', '1.0.5', require: false
  gem 'database_cleaner'
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
  gem 'webmock'
  gem 'timecop'
end

group :production do
  gem 'rails_12factor'
end